- readme.md
added readme.md and initial text
> Initial text for readme

- pom.xml
* https://hibernate.atlassian.net/browse/BVAL-539
> BVAL-539 Set the version of the maven-deploy-plugin

- src/main/java/javax/validation/Validation.java
- src/test/java/javax/validation/BarValidationProvider.java
- src/test/java/javax/validation/ConstraintViolationExceptionTest.java
- src/test/java/javax/validation/FooValidationProvider.java
- src/test/java/javax/validation/examples/ConstraintValidationNodeBuilderTest.java
* https://hibernate.atlassian.net/browse/BVAL-535
> BVAL-535 Reduce the number of compilation warnings in the API

- README.md
* https://hibernate.atlassian.net/browse/BVAL-541
> BVAL-541 Update the CI link

- src/main/java/javax/validation/Constraint.java
- src/main/java/javax/validation/constraints/AssertFalse.java
- src/main/java/javax/validation/constraints/AssertTrue.java
- src/main/java/javax/validation/constraints/DecimalMax.java
- src/main/java/javax/validation/constraints/DecimalMin.java
- src/main/java/javax/validation/constraints/Digits.java
- src/main/java/javax/validation/constraints/Future.java
- src/main/java/javax/validation/constraints/Max.java
- src/main/java/javax/validation/constraints/Min.java
- src/main/java/javax/validation/constraints/NotNull.java
- src/main/java/javax/validation/constraints/Null.java
- src/main/java/javax/validation/constraints/Past.java
- src/main/java/javax/validation/constraints/Pattern.java
- src/main/java/javax/validation/constraints/Size.java
* https://hibernate.atlassian.net/browse/BVAL-544
> BVAL-544 Allow standard constraints to be used in the TYPE_USE context

- src/main/java/javax/validation/ValidatorFactory.java
- https://hibernate.atlassian.net/browse/BVAL-546
> BVAL-546 Make ValidatorFactory extend AutoClosable

- src/main/java/javax/validation/valueextraction/ExtractedValue.java
- src/main/java/javax/validation/valueextraction/ValueExtractor.java
- src/main/java/javax/validation/valueextraction/package-info.java
@gunnarmorling I went for valueextraction for the package name as it's the title of your proposal.
I added the javadoc.
> BVAL-508 Add the API for value extraction

- src/main/java/javax/validation/GroupSequence.java
- src/main/java/javax/validation/ReportAsSingleViolation.java
- src/main/java/javax/validation/executable/ValidateOnExecution.java
- src/main/java/javax/validation/valueextraction/UnwrapByDefault.java
https://hibernate.atlassian.net/browse/BVAL-568
Please tell me whether it is better to make @ExtractedValue also documented or not.
> BVAL-568 Make built-in annotations documented

- src/test/java/javax/validation/ValidationTest.java
Follow-up for https://hibernate.atlassian.net/browse/BVAL-559 (which targets 2.0-next so I didn't create another JIRA)
> BVAL-559 Add NoProviderFoundException - Test

- src/main/xsd/validation-mapping-2.0.xsd
* https://hibernate.atlassian.net/browse/BVAL-593
> BVAL-593 Allow to configure group conversions for container element types in XML

- pom.xml
- src/main/resources/java-header-style.xml
- src/main/resources/license.header
- src/main/resources/xml-header-style.xml
* https://hibernate.atlassian.net/browse/BVAL-598
> BVAL-598 Check the presence of the license using the  license-maven-plugin

- src/main/java/javax/validation/metadata/ConstraintDescriptor.java
- src/main/java/javax/validation/metadata/ValidateUnwrappedValue.java
* https://hibernate.atlassian.net/browse/BVAL-596
> BVAL-596 Move ValidateUnwrappedValue to javax.validation.metadata

- src/main/java/javax/validation/ConstraintValidatorContext.java
@gsmet Fixed the map examples and added another one for `addContainerElementNode()`.
> BVAL-592 Follow-Up

- src/main/java/javax/validation/constraints/Future.java
- src/main/java/javax/validation/constraints/Past.java
* https://hibernate.atlassian.net/browse/BVAL-656
> BVAL-656 Remove unused imports

- src/main/java/javax/validation/metadata/BeanDescriptor.java
- src/main/java/javax/validation/valueextraction/ValueExtractor.java
https://hibernate.atlassian.net/projects/BVAL/issues/BVAL-658
> BVAL-658 JavaDoc fixes

- src/main/xsd/validation-configuration-2.0.xsd
- src/main/xsd/validation-mapping-2.0.xsd
* https://hibernate.atlassian.net/browse/BVAL-685
> BVAL-685 Use the full URLs in xsi:schemaLocation of our XML files

- src/main/java/javax/validation/ClockProvider.java
- src/main/java/javax/validation/Configuration.java
- src/main/java/javax/validation/ConstraintValidatorContext.java
- src/main/java/javax/validation/ElementKind.java
- src/main/java/javax/validation/MessageInterpolator.java
- src/main/java/javax/validation/Path.java
- src/main/java/javax/validation/Validation.java
- src/main/java/javax/validation/ValidationProviderResolver.java
- src/main/java/javax/validation/Validator.java
- src/main/java/javax/validation/ValidatorContext.java
- src/main/java/javax/validation/ValidatorFactory.java
- src/main/java/javax/validation/bootstrap/ProviderSpecificBootstrap.java
- src/main/java/javax/validation/constraints/Negative.java
- src/main/java/javax/validation/constraints/NegativeOrZero.java
- src/main/java/javax/validation/constraints/NotBlank.java
- src/main/java/javax/validation/constraints/Positive.java
- src/main/java/javax/validation/constraints/PositiveOrZero.java
- src/main/java/javax/validation/executable/ValidateOnExecution.java
- src/main/java/javax/validation/metadata/BeanDescriptor.java
- src/main/java/javax/validation/metadata/ContainerDescriptor.java
- src/main/java/javax/validation/metadata/ParameterDescriptor.java
- src/main/java/javax/validation/spi/ConfigurationState.java
- src/main/java/javax/validation/valueextraction/ExtractedValue.java
- src/main/java/javax/validation/valueextraction/UnwrapByDefault.java
- src/main/java/javax/validation/valueextraction/Unwrapping.java
- src/main/java/javax/validation/valueextraction/ValueExtractor.java
- src/main/java/javax/validation/valueextraction/ValueExtractorDeclarationException.java
- src/main/java/javax/validation/valueextraction/ValueExtractorDefinitionException.java
- src/main/xsd/validation-configuration-2.0.xsd
- src/main/xsd/validation-mapping-2.0.xsd
https://hibernate.atlassian.net/browse/BVAL-604
> BVAL-604 Avoiding forced line wraps

- src/main/java/javax/validation/ConstraintViolationException.java
- src/test/java/javax/validation/ConstraintViolationExceptionTest.java
* https://hibernate.atlassian.net/browse/BVAL-703
> BVAL-703 Reallow null values in ConstraintViolationException second constructor

- src/main/java/javax/validation/BootstrapConfiguration.java
https://hibernate.atlassian.net/browse/BVAL-716
> BVAL-716 JavaDoc fixes

- pom.xml
> Add the org.eclipse.ee4j parent pom ref

- pom.xml
> Set version to 2.0.3 for initial api release

- pom.xml
> Reset jakarta-release branch version to 2.0.2

- pom.xml
> Add a link to the eclipse.org hosted EFSL license

- pom.xml
- src/main/javadoc/doc-files/speclicense.html
> Include the EFSL license rather than linking to an external source

- pom.xml
> Update footer to include copyright and bv dev list email

- README.md
Update the version in the README to 3.0
> Update version to 3.0

- pom.xml
> Update to 1.0.6 of parent pom for jakartaee staging repo changes

- pom.xml
> Prepare for 3.0.0-M1 milestone release

- pom.xml
> Reset to 3.0.0-SNAPSHOT dev version

- src/main/java/jakarta/validation/Valid.java
> FIX : minor grammar error

- pom.xml
Signed-off-by: starksm64 <starksm64@gmail.com>
> Add module-info for the 3.0.1 service release, #169

- pom.xml
- src/main/java/module-info.java
Signed-off-by: starksm64 <starksm64@gmail.com>
> Add the missing module-info file, #169

- .github/dependabot.yml
- NOTICE.md
Adds dependabot so we can keep dependencies up to date, as well as minor updates to NOTICE.md
> Adding Dependabot and NOTICE.md updates

- README.md
> Update Schema Publishing Procedure URL

- pom.xml
- Fixes https://github.com/jakartaee/validation/issues/244
> [#244] Include license and notice files in the packaged jar

- ci/snapshot-publish/Jenkinsfile
since 'basic' is the agent label ...
> [#286] Move the agent label into expected place

- ci/snapshot-publish/Jenkinsfile
- pom.xml
- add gpg signing
- fix sources/maven-central-publishing plugin configs
> [#286] More snapshot publishing updates
